[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
map <F3> :NERDTreeToggle<CR>
let NERDTreeWinPos='rightbelow'
let NERDTreeMapActivateNode='l'
let NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'preservim/nerdcommenter'
hook_add = '''
" Create default mappings
let g:NERDCreateDefaultMappings = 1

" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1

" Allow commenting and inverting empty lines (useful when commenting a region)
let g:NERDCommentEmptyLines = 1

" Enable trimming of trailing whitespace when uncommenting
let g:NERDTrimTrailingWhitespace = 1

" Enable NERDCommenterToggle to check all selected lines is commented or not
let g:NERDToggleCheckAllLines = 1

map <Space>cl :call nerdcommenter#Comment('', 'toggle')<CR>
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''
let g:coc_global_extensions = [
  \ 'coc-tsserver',
  \ 'coc-json',
  \ 'coc-pyright',
  \ 'coc-html',
  \ 'coc-css',
  \ 'coc-java',
  \ 'coc-flutter',
  \ 'coc-react-refactor',
  \ 'coc-git',
  \ 'coc-sql',
  \ 'coc-swagger',
 \ ]

if isdirectory('./node_modules') && isdirectory('./node_modules/prettier')
  let g:coc_global_extensions += ['coc-prettier']
endif

if isdirectory('./node_modules') && isdirectory('./node_modules/eslint')
  let g:coc_global_extensions += ['coc-eslint']
endif
'''

[[plugins]]
repo = 'github/copilot.vim'
hook_add = '''
map <Space>cp :Copilot panel<CR>
'''

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'sbdchd/neoformat'
hook_add = '''
map <Space>bf :Neoformat<CR>
let g:neoformat_format_on_save = 0
let g:neoformat_enabled_javascript=['prettier']
let g:neoformat_enabled_typescript=['prettier']
augroup fmt
  autocmd!
  autocmd BufWritePre * undojoin | Neoformat
augroup END
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add='''
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = ' '
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ' '
let g:airline_symbols.maxlinenr = ' '
let g:airline_symbols.dirty='⚡'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-fugitive'

