[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
let g:ale_echo_msg_format = '[%linter%] %s'
let g:ale_rust_cargo_use_check = 1
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_sign_error = "✗"
let g:ale_sign_warning = "⚠"
let g:ale_linters = {
  \ 'python': ['flake8'],
  \ 'rust': ['cargo'],
  \ 'go': ['gofmt', 'go vet'],
  \ 'cpp': ['gcc'],
  \ 'c': ['gcc'],
  \}
let g:ale_fixers = {
  \ 'python': ['black'],
  \ 'rust': ['rustfmt'],
  \ 'go': ['gofmt'],
  \ 'cpp': ['uncrustify'],
  \ 'c': ['uncrustify'],
  \}
let g:ale_fix_on_save = 1
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
map <F3> :NERDTreeToggle<CR>
let NERDTreeWinPos='rightbelow'
let NERDTreeMapActivateNode='l'
let NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'sbdchd/neoformat'
hook_add = '''
map <Space>bf :Neoformat<CR>
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add='''
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#left_alt_sep = ''
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ' '
let g:airline_symbols.maxlinenr = ' '
let g:airline_symbols.dirty='⚡'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

